### Create Element
POST http://localhost:8080/api/Educationalelement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTcxNzA5NDk0NCwiaWF0IjoxNzE3MDkxMzQ0LCJzY29wZSI6IlJPTEVfVVNFUiJ9.o8jtrHCg3Ca625hUpjEBO3R6D5l1qysD8Pg7_it5gc30XBE4ridtzzN1GBWr9WmJn0VA1C4wnvchCt5zCOQr0b3zPk7RjWbQLTUQy34qozzzbsrKmEACXMt57cMnbla7Yauwu-muBVme7dV_iFyfyXAdwppb1Ml2xzwTgpAIVjVLBzTmMVAfq6FkOZa1iDgoxzd4DLRH9AYG_r-o8YZIv92QiDUcgM_zhWJwUk4JsTySeNJSVSBzD-wBHsNvwhSb6XYG7hijde-oO_JY5aM7M5JsBqFRrmlwQhPeEtjt1HRmlBC0p7hdZloMo5yd6VUnQDMFt7NBojmctQNun90-6w


{
  "title": "java",
  "level": {
    "idLevel": 2
  },
  "professor": {
    "idPerson": 1
  },
  "coordinator": {
    "idPerson": 1
  },
  "elementType": "MODULE"
}


### Update Educationalelement
PUT http://localhost:8080/api/Educationalelement/1
Content-Type: application/json

{
  "title": "Updated Element Title",
  "level": {
    "idLevel": 2,
    "title": "Preparatory cycle 2"
  },
  "coordinator": {
    "idPerson": 2
  },
  "elementType": "ELEMENT"
}


### Delete Educationalelement
DELETE http://localhost:8080/api/Educationalelement/1
Content-Type: application/json


### Get Educationalelement
GET http://localhost:8080/api/Educationalelement/1
Accept: application/json

### Get All Educationalelement
GET http://localhost:8080/api/Educationalelement
Accept: application/json

###
