### Create Group
POST http://localhost:8080/api/Group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTcxNzA3OTE0NCwiaWF0IjoxNzE3MDc1NTQ0LCJzY29wZSI6IlJPTEVfVVNFUiJ9.WKwxbwOptQztDvWEriYFDLshz8sWt_1jVl0-ZYiWQRrLCN60C1h8Ow3OzP_GzXg_yCPpcqu85wB5Ht01aloZnmTlYDazkr-cc9hDaUodavkMmawkuwvhlz24hmFoFcDt0cGIZUyVNyNJKzY3qx5yx79Cvzwe3DulUny-IP8lzagJCtFDZj3KWd0-vLR6_Vam9baxM3Yi4hnbdf1ZLBRwmrD1NSiDPFsCbvZun9lDtDyfCeu6_xWPRNpxTbQLCBo5fZr1sJMtfHphyTYY7QOsatJ4GPTKzcAUhM_WcJVqUTGlmUyNJN6nUsFSe6UlIOaBBRS8DfprHul7Rp_WorhfGw

{
  "title": "funnn",
  "description": "A group for fun  "

}
### Update Group
PUT http://localhost:8080/api/Group/1
Content-Type: application/json

{
  "description": "updated description"
}

### Delete Group
DELETE http://localhost:8080/api/Group/1
Content-Type: application/json

### Get Group
GET http://localhost:8080/api/Group/1
Accept: application/json

### Get All Groups
GET http://localhost:8080/api/Group
Accept: application/json

### Create groups of professors
PUT http://localhost:8080/api/Group/2/addProfessortogroup
Content-Type: application/json

[1,2]


###
