

POST http://localhost:8080/api/monitorings

{
  "dateExam": "03-05-2024",
  "coordinator": {
    "idPerson": 1
  },
  "room": {
    "idRoom": 1
  },
  "exam": {
    "idExam": 1
  }
}


###
### Create Monitoring
POST http://localhost:8080/api/monitorings
Content-Type: application/json


{
  "dateExam": "03-05-2024",
  "room": {
    "idRoom": 2
  },
  "exam": {
    "idExam": 2
  }
}

//
//  "administrator": {
//    "idPerson": 4
//  },
//#{{
//#  "dateExam": "03-05-2024",
//#  "administrator": {
//#    "idPerson": 2
//#  },
//#  "room": {
//#    "idRoom": 1
//#  },}
//#  "exam": {
//#    "startTime": "10",
//#    "endTime": "12",
//#    "preuve": "Path//",
//#    "element": {
//#      "idElement": 1
//#    }
//#  }
//#}

### Update Educationalelement
PUT http://localhost:8080/api/monitorings/1
Content-Type: application/json

{
  "title": "Updated Element Title",
  "level": {
    "idLevel": 2,
    "title": "Preparatory cycle 2"
  },
  "coordinator": {
    "idPerson": 2
  },
  "elementType": "ELEMENT"
}


### Delete Monitoring
DELETE http://localhost:8080/api/monitorings/1
Content-Type: application/json


### Get Monitoring
GET http://localhost:8080/api/monitorings/1
Accept: application/json

### Get All Monitoring
GET http://localhost:8080/api/monitorings
Accept: application/json

### get Monitoring by date
GET http://localhost:8080/api/monitorings/date/03-05-2024T08:00:00
Accept: application/json

### add professors to monitoring
PUT http://localhost:8080/api/monitorings/1/addProfessorsToMonitoring
Content-Type: application/json

1


