### Create Monitoring
POST http://localhost:8080/api/monitorings?nbrMonitors=2
Content-Type: application/json

{
  "dateExam": "03-05-2024",
  "room": {
    "idRoom": 1
  },
  "exam": {
    "idExam": 1
  }
}


### Update Monitoring
PUT http://localhost:8080/api/monitorings/1
Content-Type: application/json

{
  "dateExam": "03-06-2024"
}


### Delete Monitoring
DELETE http://localhost:8080/api/monitorings/1
Content-Type: application/json


### Get Monitoring
GET http://localhost:8080/api/monitorings/1
Accept: application/json

### Get All Monitoring
GET http://localhost:8080/api/monitorings
Accept: application/json

### get Monitoring by date
GET http://localhost:8080/api/monitorings/date/03-06-2024
Accept: application/json



