### Create Personnel A
POST http://localhost:8080/api/personnel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTcxNzA5NDk0NCwiaWF0IjoxNzE3MDkxMzQ0LCJzY29wZSI6IlJPTEVfVVNFUiJ9.o8jtrHCg3Ca625hUpjEBO3R6D5l1qysD8Pg7_it5gc30XBE4ridtzzN1GBWr9WmJn0VA1C4wnvchCt5zCOQr0b3zPk7RjWbQLTUQy34qozzzbsrKmEACXMt57cMnbla7Yauwu-muBVme7dV_iFyfyXAdwppb1Ml2xzwTgpAIVjVLBzTmMVAfq6FkOZa1iDgoxzd4DLRH9AYG_r-o8YZIv92QiDUcgM_zhWJwUk4JsTySeNJSVSBzD-wBHsNvwhSb6XYG7hijde-oO_JY5aM7M5JsBqFRrmlwQhPeEtjt1HRmlBC0p7hdZloMo5yd6VUnQDMFt7NBojmctQNun90-6w



{
  "firstName": "hind",
  "lastName": "mt",
  "cin": "XNZoes7sjv8",
  "type": "Administrator",
  "grade": "secretaire"
}

### Create Personnel P
POST http://localhost:8080/api/personnel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTcxNzA5NDk0NCwiaWF0IjoxNzE3MDkxMzQ0LCJzY29wZSI6IlJPTEVfVVNFUiJ9.o8jtrHCg3Ca625hUpjEBO3R6D5l1qysD8Pg7_it5gc30XBE4ridtzzN1GBWr9WmJn0VA1C4wnvchCt5zCOQr0b3zPk7RjWbQLTUQy34qozzzbsrKmEACXMt57cMnbla7Yauwu-muBVme7dV_iFyfyXAdwppb1Ml2xzwTgpAIVjVLBzTmMVAfq6FkOZa1iDgoxzd4DLRH9AYG_r-o8YZIv92QiDUcgM_zhWJwUk4JsTySeNJSVSBzD-wBHsNvwhSb6XYG7hijde-oO_JY5aM7M5JsBqFRrmlwQhPeEtjt1HRmlBC0p7hdZloMo5yd6VUnQDMFt7NBojmctQNun90-6w

{
  "firstName": "hamza",
  "lastName": "hn",
  "cin": "XNZos7sjv8",
  "type": "Professor",
  "speciality": "uml",
  "idDepartement": 1,
  "idSector": 1
}

### Update Personnel
PUT http://localhost:8080/api/personnel/1
Content-Type: application/json

{
  "firstName": "hanane"
}

### Delete Personnel
DELETE http://localhost:8080/api/personnel/1
Content-Type: application/json

### Get Personnel
GET http://localhost:8080/api/personnel/1
Accept: application/json

### Get All Personnel
GET http://localhost:8080/api/personnel
Accept: application/json

###
