### Create Personnel A
POST http://localhost:8080/api/personnel
Content-Type: application/json


{
  "firstName": "hind",
  "lastName": "hhh",
  "cin": "T131424386",
  "email": "hind-hayat@gmail.com",
  "type": "Administrator",
  "grade": "secretaire"
}


### Create Personnel (Professor)
POST http://localhost:8080/api/personnel
Content-Type: application/json

{
  "firstName": "hanane",
  "lastName": "hn",
  "cin": "R131525586",
  "email": "hagane_nadi@gmail.com",
  "type": "Professor",
  "speciality": "java",
  "idDepartement": 1,
  "idSector": 1
}

### Update Personnel
PUT http://localhost:8080/api/personnel/1
Content-Type: application/json

{
  "firstName": "Abdo"
}

### Delete Personnel
DELETE http://localhost:8080/api/personnel/1
Content-Type: application/json

### Get Personnel
GET http://localhost:8080/api/personnel/2
Accept: application/json

### Get All Personnel
GET http://localhost:8080/api/personnel
Accept: application/json

###
